### ISSUE TITLE
Issues with newer firmware?

### ISSUE THREAD

**Issue by SukkoPera** [vdudouyt/minipro#105]
I have been using my TL866 for a bit exclusively under Linux with satisfaction, it was always working fine.

Then I connected it to a Windows machine, and the Autoelectric software updated it. Since then I am having lots of issues under Linux. It clearly goes "too fast" and 90% of the time it doesn't program EPROMs correctly.

Firmware version:

    Found Minipro TL866CS v03.2.81

**Comment by SukkoPera** [comment]
Sorry, I'm pretty sure this was due to a bad adapter.

**Comment by DavidGriffith** [comment]
@SukkoPera So, were you successful in writing and reading chips with the very latest firmware?

**Comment by SukkoPera** [comment]
With the version mentioned above, yes.
