### ISSUE TITLE
Intel HEX output format needed

### ISSUE THREAD

**Issue by szg0000** [vdudouyt/minipro#114]
A command switch is needed to open/save the file in Intel HEX format.

**Comment by chenz** [comment]
Maybe it would be better to go the Unix way and implement piping, and leave format conversion to external tools, ie srecord [http://srecord.sourceforge.net/].

**Comment by DavidGriffith** [comment]
The code to do this is extremely simple.  I'm looking at adding an ```-f``` flag to indicate what sort of hex format to use.  For instance: ```minipro -p "M27C256B @DIP28" -r foobar.hex -f i8``` for Intel I8HEX.
