### ISSUE TITLE
New TL866II Plus Support

### ISSUE THREAD

**Issue by ee-muhammad** [vdudouyt/minipro#118]
As per autoelectric.cn, both TL866A and CS variants are now discountiued.

TL866II Plus is the upgraded model now, for which company offers separate pc application for windows pcs

Would this project be still compatible with new product?

**Comment by ee-muhammad** [comment]
That discussion already there.
Sorry for that

**Comment by sampablokuper** [comment]
See https://github.com/vdudouyt/minipro/issues/101
