### ISSUE TITLE
After upgrading programmer to V03.2.86, code no longer works

### ISSUE THREAD

**Issue by ddandare** [vdudouyt/minipro#126]
After upgrading the firmware of the TL866CS programmer with the official application from the vendor (Minipro 6.85), code no longer works, throwing a "IO error: bulk_transfer: LIBUSB_ERROR_OVERFLOW"

**Comment by DavidGriffith** [comment]
Please go to https://gitlab.com/DavidGriffith/minipro/.  This repository is no longer maintained.
