### ISSUE TITLE
check device ID

### ISSUE THREAD

**Issue by drforbin** [vdudouyt/minipro#20]
I'm trying to read out a DS1645 for a tds520 scope I'm fixing.
The DS1245  is listed as supported. they are the same except one is larger than other.
Is there anyway to disable device ID check with your tools like in the GUI version?

Thanxs...
Great work FYI.
Always want to use linux/bsd vs WINBLOWS

**Comment by d3cline** [comment]
We need the ability to disable device ID and to read device ID, that way we can write new definitions, but without tests, or while flashing a chip on board, the chip ID is pretty critical as a flag.

**Comment by chenz** [comment]
The `-y` option was added some time after this discussion.

**Comment by d3cline** [comment]
thanks, i will have to rebuild.
