### ISSUE TITLE
Problem programming 16f84

### ISSUE THREAD

**Issue by peterlavelle** [vdudouyt/minipro#26]
Hi,

Could just be me being a noob, but I am having problems burning a hex file compiled using mpasmx to a PIC16F84. When I try to burn the firmware to the uC, I get the error below:

pete@xps:~/pic16f84/blink$ minipro -p pic16f84 -c code -w hex/blink.hex 
Found Minipro TL866CS v3.62.2
Incorrect file size: 200 (needed 2048)

When I disassemble the hex file, I get the listing below. 

000000:  280d  goto 0xd
000001:  0181  clrf 0x1
000002:  0801  movf 0x1, w
000003:  3c20  sublw    0x20
000004:  1d03  btfss    0x3, 0x2
000005:  2802  goto 0x2
000006:  3400  retlw    0
000007:  0181  clrf 0x1
000008:  0801  movf 0x1, w
000009:  3c10  sublw    0x10
00000a:  1d03  btfss    0x3, 0x2
00000b:  2808  goto 0x8
00000c:  3400  retlw    0
00000d:  1683  bsf  0x3, 0x5
00000e:  301f  movlw    0x1f
00000f:  0085  movwf    0x5
000010:  3000  movlw    0
000011:  0086  movwf    0x6
000012:  3007  movlw    0x7
000013:  0081  movwf    0x1
000014:  1283  bcf  0x3, 0x5
000015:  0185  clrf 0x5
000016:  0186  clrf 0x6
000017:  1406  bsf  0x6, 0
000018:  2007  call 0x7
000019:  1006  bcf  0x6, 0
00001a:  2817  goto 0x17
002007:  3ff0  addlw    0xf0

A quick search on google doesn't bring up anyone else having the same problem, which makes me think I'm doing something stupid, so sorry of this is just a waste of everyone's time.

**Comment by flok99** [comment]
I've got a somewhat same problem:
Found Minipro TL866CS v3.63.2
Incorrect file size: 16400 (needed 2046)

**Comment by bradgrantham** [comment]
I believe you're supposed to be using "miniprohex" variant to burn hex files.

**Comment by defendrok** [comment]
Pretty the same problem over here, however I am using miniprohex
`sudo miniprohex -p "PIC18F4520" -w main.hex` with the code compiled with `gpasm`

Getting this error message:
`Incorrect file size: 3145742 (needed 32768)`

hex file is 126 bit long... don't even know what to do

**Comment by bradgrantham** [comment]
Hey, @defendrok, I couldn't get miniprohex to work in the end.  (Probably pulled in the wrong tools in MacPorts...)

Here's what I've figured out, which is a little hacky, but may help.  Writing a PIC with minipro requires writing both the code region starting at 0x0 (size dependent on PIC) and the data region ("config" in PIC terms) starting at 0x300000 (also size dependent on PIC).

SDCC and XC8 both output .HEX files containing these regions.

My friend @lkesteloot and I hacked a .HEX reader for a separate project which can extract binary blobs from HEX files.  I’ve just put this reader online at https://github.com/bradgrantham/hex2bin .

For a PIC18F452, here’s the sequence I used for a HEX file named “main.hex”:
```
hex2bin -r 32768 0 main.hex main.code.bin
hex2bin -r 256 0x300000 main.hex main.config.bin

minipro -p PIC18F452 -c code -w main.code.bin
minipro -p PIC18F452 -e -c data -w main.config.bin
```

The size of the region you need to extract with hex2bin for code depends on the PIC, but the good news is that minipro will tell you right away if it’s the wrong size.

(I don't feel super-confident about this, your mileage may very, safety not guaranteed, you may fry your PIC, etc, etc.  It's probably better to use "official" PIC software and programmer for best results.)

**Comment by defendrok** [comment]
@bradgrantham Thank you very much! I've managed to write a code section. At least something after a week of struggling. Don't you know any other way, without utilizing different hacks on *nix systems?

**Comment by bradgrantham** [comment]
@defendrok No, sorry, I moved to MPLAB and C and have been burning from there with a CanaKit UK1300, in-circuit.  That's a better experience all around!  (Except now I think I'm encountering a PIC assembler error.)

**Comment by szmood** [comment]
Hi everybody, I got the exact problem but with an Atmel Atmega328p.
I tried the suggested workaround with hex2bin:
`hex2bin -r 32768 0 main.hex`
But the size will only depend on how big the hex file is, how did you guys alter the size?

**Comment by bradgrantham** [comment]
I don't know anything about ATmega328p.  You need to know how big the data areas are that you're programming and their addresses.

For each run, hex2bin will extract whatever bytes are in the hex file in the area you've specified (ignoring anything outside that area), and fill the rest with 0xFF.  (Should hex2bin have an option to set the fill byte?)

For example, if the hex only has 2048 bytes starting at 0x1000, and you specify "hex2bin -r 32768 0x1000", then hex2bin will write those 2048 bytes then 30720 bytes of 0xFF into the output file.  If you specify "hex2bin -r 16384 0", then hex2bin will write 4096 bytes of 0xFF, then the 2048 bytes from the hex file, and then 10240 bytes of 0xFF.

Also make sure you're using commit a7553c7 of hex2bin or later, I fixed a bad bug in that commit.

**Comment by szmood** [comment]
Updated hex2bin to current version, everything works fine now. Thank you!
I also found another way around the problem in Minipro. Remove line 254-256 and line 405-419 in main.c and then remake.

**Comment by peterlavelle** [comment]
Thanks mate, much appreciated.

**Comment by DavidGriffith** [comment]
It looks like with an updated hex2bin, the problem is fixed.  I'll check the suggested lines in main.c and then decide if this issue can be closed.

Also, I think I fixed the problems reported here about miniprohex with Pull #88.

**Comment by scimad** [comment]
The issue still persists while I am programming my at89c52.

**Comment by DavidGriffith** [comment]
Please file a new issue at https://gitlab.com/DavidGriffith/minipro/
