### ISSUE TITLE
Emit a list of supported devices

### ISSUE THREAD

**Issue by DavidGriffith** [vdudouyt/minipro#29]
It would be nice if I could do "minipro -l | less" to get a list of all devices supported so I can be sure I select exactly the right device name.

**Comment by vdudouyt** [comment]
Hi,

You can easily get a list by using 'minipro -p help'. It will automatically open a pager program when running from a pty.

Best Regards,

Valentin

**Comment by DavidGriffith** [comment]
I see.  I'm getting ready to submit a pull request to document stuff like this, among other stuff.
