### ISSUE TITLE
dpkg-buildpackage fails with missing libusb dependency info (error #2)

### ISSUE THREAD

**Issue by buchty** [vdudouyt/minipro#32]
Can be solved by adding the following to debian/rules as a quick fix:

override_dh_shlibdeps:
    dh_shlibdeps --dpkg-shlibdeps-params=--ignore-missing-info

**Comment by chenz** [comment]
I cannot reproduce this on Debian 8.6 or Ubuntu 12.04. Also, if the info was missing - would that not be a bug in the libusb package?
