### ISSUE TITLE
Downloadable release source archive (with a version number)

### ISSUE THREAD

**Issue by ranauei** [vdudouyt/minipro#33]
Hello I'd like to add this utility to MacPorts and it gets complicated without a versioned source archive (I can't use the generic master zip file that github provides I need one with a version number in it). It'll be really nice if you could provide one.

**Comment by vdudouyt** [comment]
Hi!

I uploaded it as a .tar.gz archive into https://github.com/vdudouyt/minipro/releases. Is it now enough to be packaged in MacPorts?

Best Regards,

Valentin

**Comment by ranauei** [comment]
Sorry but the file I'm getting is a 5mb blob that seems to be a cat of all the files in the repo :(

**Comment by ranauei** [comment]
Thanks I created and submitted the new MacPort

**Comment by ranauei** [comment]
Minipro is now available on MacPorts (committed today).
