### ISSUE TITLE
Warning: firmware is too old??

### ISSUE THREAD

**Issue by dburr** [vdudouyt/minipro#39]
I recently purchased a Minipro TL866A and found this software. Thank you for making it! I just installed it on my Ubuntu laptop and it compiled and installed correctly. As a test I tried reading the contents of an AM27C128 @DIP28 EPROM I had lying around (the ROM chip from my Replica I) and that seemed to work correctly (so far anyway.. I have yet to try writing to an EPROM) However I get the message "Warning: firmware is too old" My device is recognized as a Minipro TL866A v3.58.2. Will this software still work with my older firmware, or is there a problem and should I upgrade to a newer firmware? If so, can someone provide a direct link to it? The only sites I am able to find are in Chinese, which I do not speak/read, and the Google translation is somewhat lacking, and I have had no luck navigating them.

**Comment by vdudouyt** [comment]
Hi Donald,

I believe that it shouldn't be a problem unless you try to flash something that was added after your firmware version was released.

Cheers!
Valentin
