### ISSUE TITLE
AM28F020A support?

### ISSUE THREAD

**Issue by alexforencich** [vdudouyt/minipro#48]
I have a whole tube of these things, but it seems that only the AM28F020 is supported.  The AM28F020A has a built-in sequencer that does most of the work, simplifying the erase and program process.  However, this makes it completely incompatible with the AM28F020 mode.  Since it is a much simpler protocol, it should not be very difficult to implement.

**Comment by elosha** [comment]
You could try to use a EEPROM device protocol. Just make sure it uses the same programming voltage as your device and ignore id mismatch. If it works, I suggest someone could duplicate that device and replace the id.

**Comment by DavidGriffith** [comment]
@alexforencich Are you still here?  What package are your chips in?  I'd like to get one of those chips to play with.
