### ISSUE TITLE
Doesn't seem to work on OS X El Capitan

### ISSUE THREAD

**Issue by samw3** [vdudouyt/minipro#49]
I've installed libusb using brew.  I then build with the Makefile.osx, and everything seems to go fine.  I then plug in my TL866CS programmer from autoelectric.cn with a W27C512 int the 40 pin and run this command line. 

./minipro -p "W27C512 @DIP28" -r "test.hex"

Nothing is printed and the command never returns.  However, if I unplug the programmer, I get:

IO error: bulk_transfer: LIBUSB_ERROR_IO

Any ideas?

**Comment by samw3** [comment]
I did some debugging,  it hangs on:
    msg_recv(handle, buf, 40);
in minipro_get_system_info

**Comment by samw3** [comment]
Further:

	ret = libusb_bulk_transfer(handle->usb_handle, (1 | direction), buf, length, &bytes_transferred, 0);

inside msg_transfer is the point it hangs, though it doesn't previously go through that line.  Though never as a read.

**Comment by peternoyes** [comment]
I can reproduce this issue. I am trying:
minipro -p "AT28C256 @SOIC28" -w test.bin

The RUN light blinks once, but then nothing happens.

**Comment by samw3** [comment]
@peternoyes It appears to be an Apple bug.  The libusb team submitted a bug report to Apple but we haven't seen a fix yet.  See here: https://github.com/libusb/libusb/issues/123

**Comment by d235j** [comment]
This appears to be fixed with in 10.11.4 Beta 2.

**Comment by samw3** [comment]
It is indeed fixed in 10.11.4
