### ISSUE TITLE
Version number mismatch compared to Windows app

### ISSUE THREAD

**Issue by Malvineous** [vdudouyt/minipro#51]
I just started using my new TL866A and I had to upgrade the firmware, however while this program worked fine, I noticed that it is reporting a different version number to the Windows application:

Before the reflash the Windows program reported device firmware 3.2.58, while this application reported 3.58.2.  After the reflash the Windows program told me I was now on firmware version 3.2.72, while this app is reporting 3.72.2.

Hopefully it's just a simple matter of swapping the version numbers so it's consistent with the Windows app!

**Comment by tomsim** [comment]
Fix all ready exist from 9 Jan : https://github.com/vdudouyt/minipro/pull/50 
I do not know why it is not merged yet?

**Comment by vdudouyt** [comment]
@tomsim sorry, I merged it now.

**Comment by tomsim** [comment]
@vdudouyt You can close this issue
