### ISSUE TITLE
Support for Microchip new devices (12LF1820/12LF1844)?

### ISSUE THREAD

**Issue by ClaudioLori** [vdudouyt/minipro#56]
Hi all,
I'm new on gitHub, how can add support for a new device in minipro?
Thank you so much

Claudio

**Comment by ClaudioLori** [comment]
Sorry, I forgot some info:
Programmer TL866CS with the latest version of firmware.

**Comment by kutis96** [comment]
Are they supported in the official firmware?
Unless they are, there is AFAIK no way besides rewriting the MiniPro's firmware to add new parts.
