### ISSUE TITLE
Power up / power off target device

### ISSUE THREAD

**Issue by szg0000** [vdudouyt/minipro#67]
After ICSP programming need an option to power up/power off the device with ICSP VCC pin.

**Comment by scotty264** [comment]
If I comprehend your question; is that not already supported with the "-i" and "-I" options?  Or are you speaking about a separate option to allow switching the VCC on and off regardless of the programming function?

Peace and blessings,
Scott

**Comment by szg0000** [comment]
" switching the VCC on and off regardless of the programming function."
Yes, i want to power up the device without programming function.
