### ISSUE TITLE
Is support for DS12887A (PC BIOS/CMOS) chips possible?

### ISSUE THREAD

**Issue by Malvineous** [vdudouyt/minipro#69]
I am wondering whether it is possible to add support for the Dallas DS12887A and similar chips, used on many older PC motherboards for storing settings and the clock when the PC is switched off.

Technically this is a non-volatile RAM chip (has an internal battery) so it would be nice to be able to read and write the contents with the TL866 but I am not sure how flexible the devices are.

Are all the read/write algorithms in the minipro software, or are they stored in the TL866 firmware?

**Comment by vdudouyt** [comment]
Hello,

Sorry for the late reply.

> Are all the read/write algorithms in the minipro software, or are they stored in the TL866 firmware?

Unfortunately they are stored in TL866 firmware.
