### ISSUE TITLE
Testing 6116 RAM

### ISSUE THREAD

**Issue by Phillrb** [vdudouyt/minipro#71]
Hi, how would you go about testing a 6116 RAM with this command line tool? Is there a particular file to write and read back or a function to invoke? I have it successfully compiled for macOS 10.12.

**Comment by elosha** [comment]
It seems there currently is no exclusive testing procedure in the code, unlike the original Windows tool, which is able to test RAM with various patterns.

But in theory, you could rely on the write-and-verify procedure.

1. Generate a random binary file of 16 Kbit = 2 Kbyte with dd:
`dd if=/dev/urandom of=mytestfile.bin bs=2k count=1`
2. Then write it to the device and hope that verification works:
`minipro -p 6116 -w mytestfile.bin`

I just tried this with a 62256 (tested good by the MiniPro Windows tool) and it doesn't work:
```
$ dd if=/dev/urandom of=62256rand.bin bs=32k count=1
1+0 records in
1+0 records out
32768 bytes transferred in 0.003564 secs (9194471 bytes/sec)
$ minipro -p 62256 -w 62256rand.bin 
Found Minipro TL866A v03.2.80
Writing Code...  0%
```
Here it stalls.
