### ISSUE TITLE
Testing TTL chips

### ISSUE THREAD

**Issue by slseed1969** [vdudouyt/minipro#77]
The TL866 is capable of testing IC chips with the Windows app. Is it possible to use the minipro command to test TTL's such as the 74HC86? I see that the chip is listed in the supported output, but how do I verify that it is working? Is it just a matter or reading it and comparing the hex output to a known good chip?

**Comment by elosha** [comment]
Currently, there is no dedicated testing procedure for logic ICs implemented.

I just tried what you suggested with two [CD4051 multiplexers](http://www.ti.com/product/CD4051B):
```
$ minipro -p 4051 -r cd4051-1.bin
Found Minipro TL866A v03.2.80
Reading Code... OK
Reading Data... OK
$ minipro -p 4051 -r cd4051-2.bin
Found Minipro TL866A v03.2.80
Reading Code... OK
Reading Data... OK
$ diff cd4051-1.bin cd4051-2.bin 
[no difference]
```
Contents of both files (hex):
``36 30 31 31 34 39 33 32 43 30``

But it also read the data area (which?) and dumped a 41KB `eeprom.bin`:
```
36 30 31 31 34 39 33 32 43 30 44 35 38 31 35 41
30 46 43 30 33 46 45 32 38 44 44 34 46 46 35 38
75 3A 03 A0 21 D6 4F 5C 0D B2 DB 58 39 CE A7 94
A5 2A B3 10 51 C6 FF CC 3D A2 8B C8 69 BE 57 04
D5 1A 63 80 81 B6 AF 3C 6D 92 3B 38 99 AE FF 0B
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[recurring]
``` 
Like a full lenght version of the above. It doesn't work very elegantly, but maybe it's a starting point.

If it happens that this method works accross manufacturer and technology variations, we could think about supplying a checksums for logic ICs in the device DB.
