### ISSUE TITLE
Duplicate entries in devices.h

### ISSUE THREAD

**Issue by rjwalsh** [vdudouyt/minipro#8]
While working on the OS X port, I noticed that the devices.h entry for the M27C4001 @DIP32 was duplicated in the devices.h file. I wrote a python script to parse the file and print out any duplicate entries. When I run it, I see 1554 duplicate entries. Some are in there twice and some three times.

I put the script here: https://gist.github.com/rjwalsh/d85b898fa27a54034a22

**Comment by DavidGriffith** [comment]
Duplicate of #64
