### ISSUE TITLE
Device query option?

### ISSUE THREAD

**Issue by inflex** [vdudouyt/minipro#95]
Apologies if I've missed something blatantly obvious,  is there a way to query what device is in the programmer (ie, if the markings have been scrubbed off the chip) ?

**Comment by DavidGriffith** [comment]
There is no universal way of identifying a chip that way.  Some means of identifying a chip use high voltages on certain pins.  That may be acceptable for a particular class of chips, but may damage a different class. That was the concern that led to Pull #93.

**Comment by inflex** [comment]
Thank you for the quick reply.  That's understandable.
