### ISSUE TITLE
Floating point exception error

### ISSUE THREAD

**Issue by szg0000** [vdudouyt/minipro#96]
I you give `minipro -p "GAL16V8" -r readfile.jed` minipro returnes with Floating point exception error.

**Comment by DavidGriffith** [comment]
What's the maker and part number of the chip?  Can you post an example jed file?

**Comment by szg0000** [comment]
The chip doesn't  matter. Just type this command with or without the chip.
Can you reproduce this bug? I am on P4, 32 bit system.

**Comment by szg0000** [comment]
Same problem with x86_64.

**Comment by DavidGriffith** [comment]
I've confirmed this bug.

```
$ minipro -p "GAL16V8" -r foo.jed
Found Minipro TL866A v03.2.80
Floating point exception
$
```

**Comment by DavidGriffith** [comment]
The FPE occurs at line 194 in main.c in read_page_ram().

```
/* RAM-centric IO operations */
void read_page_ram(minipro_handle_t *handle, unsigned char *buf, unsigned int type, const char *name, int size) {
        char status_msg[24];
        sprintf(status_msg, "Reading %s... ", name);

        device_t *device = handle->device;
        int blocks_count = size / device->read_buffer_size;  /* FPE happens here */
        if(size % device->read_buffer_size != 0) {
                blocks_count++;
        }
```

**Comment by DavidGriffith** [comment]
The FPE happens because in ```devices.h```,  ```read_buffer_size``` for GAL16V8 is 0x00.  This is also true for several other devices, all GALs.  Similarly, these devices also have 0x00 for ```write_buffer_size```.  Attempting to write to a GAL will also result in a FPE because of line 224 in main.c in ```write_page_ram()```.

```
void write_page_ram(minipro_handle_t *handle, unsigned char *buf, unsigned int $
        char status_msg[24];
        sprintf(status_msg, "Writing %s... ", name);

        device_t *device = handle->device;

        int blocks_count = size / device->write_buffer_size;
        if(size % device->write_buffer_size != 0) {
                blocks_count++;
        }
```

**Comment by DavidGriffith** [comment]
Would someone who better knows the low-level details of writing a GAL please comment on this?  Why are the read and write buffer sizes set to zero?

**Comment by szg0000** [comment]
Analyze the communication between the Minipro and the Windows [software](http://www.autoelectric.cn/MiniPro/minipro_setup670.rar) with [wireshark](https://www.wireshark.org/).

**Comment by rozhuk-im** [comment]
IMHO, if db contain write_buffer_size=0 or read_buffer_size=0 then, may be we should try to read/write whole size that user request.
